### PR TITLE
General fixes

### PR DESCRIPTION
**Pull request by Kirksten3**
NOTE: Not all of this update is really necessary. I just figured it would be better to use as much HTML as we could instead of JS. I generally prefer to use multipart rather than JSON for interoperability of the website. There's a lot more overhead with using JavaScript and AJAX to send these requests as well as more potential network issues and somewhat faster on a minuscule level.

**I recommend not accepting this until everyone has a chance to review and comment. If wanted that is.**

HTML tags now have required attributes which forces to be added instead of analyzing form content. 

This updates the post from the create view to use multipart encoding (use POST not JSON to update). 

Uses name field to handle post parameters.

Renders index on classes/add now with a new bar that shows the class is being created.

Ignores favicon.ico request.

Cleaned up JS a little bit.

### CODE REVIEW

**Comment by Kirksten3** [comment]
I've also added some handling on improper navigation to /classes/add. I think this would be pretty hard to do - someone would probably have to use a third party utility to post without the required params. But now I have it check req.body and a param. Since all the params are linked in the HTML page, if one is there the rest are.

And now, I have also made sure that anything with spaces will have quotes around it in the shell command as with this method it wasn't stored as JSON.

**Comment by morgaalb** [comment]
This looks good, but I'm not sure why you would remove some of the server-side error checking. I haven't tested it, but I think that someone could use curl or a similar utility to create a post request with without, for example, and 'email' attribute, and crash the server. Whether there is error checking on the client side is irrelevant.

Also, there's no need to put quotes around things with spaces. The whole point of using the shellescape library is that it does that work for you.

**Comment by Kirksten3** [comment]
That's fair, I guess it is valid to keep it. I was going back and forth on creating a require_params function. But it probably should be put back in. 

As for the quotes, perfect I wasn't sure or not if the shell escape did that. What I was briefly looking at from my console output had me worried. I'll update the changes later

**Comment by morgaalb** [comment]
By the way, the 'required' attribute is way better than the JavaScript error-checking I had. I wasn't aware you could do that. Nice work.

**Comment by morgaalb** [comment]
With the exception of the little things I mentioned above, this work looks very good. I'm going to merge it so I can begin work on other tasks. The issues I mentioned above should resolve themselves when I migrate the project to using MySql.

**Comment by millelog** [comment]
Alright yeah this fixed pretty much all of the problems we were having except the restart. I've been spinning in loops trying to configure a delete or update function to it but I'm really just not good with how mongo db functions, let alone interacts with express. 

So without a way to test any of the stuff I tried with the mongo db I'm pretty much just deleting that branch (mine, not the mongo db one) and keeping this one up on the jupyter machine as it functions correctly with an f5 after class creation. Hopefully we can just demo both versions and it'll make our project even stronger for trying to implement the same thing in different ways.

**Comment by morgaalb** [comment]
Just a quick note: you can access the db by following the VPN instructions here http://oregonstate.edu/helpdocs/network-and-phone/virtual-private-network-vpn

**Comment by millelog** [comment]
Yeah I know, I was having difficulty with it on ubuntu. But if fixed the restart issue by just taking it out of the python script and having it execute as a shell script right after the confirmation of class creation is rendered, so problem solved. Doesn't even need a refresh anymore and only shows a 502 in console for a brief second before its back up.

**Comment by Kirksten3** [comment]
So the entire script runs through? Does it return 502 in the node console?

**Comment by millelog** [comment]
let me clear my old tests and do a final one but yeah the only thing that pops up as a 502 is that stupid favicon thing because its spinloop breaks when the server restarts, is there a better way to handle that then just putting nothing in the express?

**Comment by Kirksten3** [comment]
That's strange. It should catch all requests for the favicon, even on reboot. I have an idea though, maybe we could return a status 200 on all requests. Then it wouldn't return anything but would return successful. Worth a shot?

**Comment by millelog** [comment]
damn, it kills all the resources (images, javascript for the dropdown etc...) until you refresh. Which is weird you would think those would be stored client side... Good idea though, I'll have it return 200

**Comment by millelog** [comment]
So i think the resource issue has to do with the fact that we are rendering the index page, but our url is still /create/add and therefore doesn't have the right pathing to those images.

**Comment by Kirksten3** [comment]
Well i ran into that problem too. It happened when I was trying to redirect to the index page and then pass arguments to it. It kept trying to render new headers after the old headers had been sent. The compromise was rendering the index page on the /create/add page. There might be a better option but I couldn't find one.

**Comment by millelog** [comment]
I'll just make the resource paths in the index page absolute then

**Comment by morgaalb** [comment]
Why does it matter if the favicon request returns 200? If there's no favicon, it turns a 404 when the browser requests it. Isn't that working as intended?

**Comment by Kirksten3** [comment]
It doesn't really. I just did that path loop so that it wouldn't bother me while testing. In regards to the resources that might be the best bet

**Comment by millelog** [comment]
alright seems to work now, try to make a class and see if anything goes wrong I guess.

**Pull request merged**
